function [scaled_kspace] = ModifyImageResolution(fftshifted_kspace_image,delta_resolution)
    delta_pix = abs(round(size(fftshifted_kspace_image,1)*(1-delta_resolution)/2)); %Asumes cube image
if(delta_resolution>1)
    %Increase image resolution by zero padding
    scaled_kspace = padarray(fftshifted_kspace_image, ...
        [delta_pix delta_pix delta_pix],0,'both');
else
    %Decrease image resolution by cropping kspace
    scaled_kspace = fftshifted_kspace_image( ...
        delta_pix+1:size(fftshifted_kspace_image,1)-delta_pix,...
        delta_pix+1:size(fftshifted_kspace_image,1)-delta_pix,...
        delta_pix+1:size(fftshifted_kspace_image,1)-delta_pix);
end
